version: "3.9"

services:
  aws-api:
    build:
      context: ./aws-api
    container_name: finanzapp_aws_api
    ports:
      - "8080:8080"
    env_file:
      - ./aws-api/.env
    restart: unless-stopped

networks:
  default:
    name: finanzapp_net
