version: "3.9"

services:
  ocr-api:
    build:
      context: ./ocr-api
    container_name: finanzapp_ocr
    ports:
      - "8000:8000"
    restart: unless-stopped

  gpt-api:
    build:
      context: ./gpt-api
    container_name: finanzapp_gpt
    # El puerto 8080 se define en main.py (FastAPI)
    ports:
      - "8080:8000"
    # Monta la carpeta del modelo para no copiar 4 GB en la imagen
    volumes:
      - ./models:/models
    environment:
      - MODEL_PATH=/models/nous-hermes-2-mistral-7b-dpo.Q4_K_M.gguf
    restart: unless-stopped

networks:
  default:
    name: finanzapp_net
